pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                echo "Welcome to Jenkins Pipeline via Jenkins FIle"
                echo "Starting to Build our TomCat Project"
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deply to Staging'){
            steps {
                echo "We are going to deploy to staging server"
                Build job: 'deploy-tomcat-staging'
            }
        }
}
}